apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-dev
spec:
  destination:
    namespace: spring-petclinic-dev
    server: https://kubernetes.default.svc
  project: janus
  source:
    helm:
      valueFiles:
       - values.yaml
    path: helm
    repoURL: https://github.com/rhdh-orchestrator-test/aaaaa-gitops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
